package cmpe131.cmpebookproject.book;

public enum Genre {
    MYSTERY, FICTION, COMEDY, DRAMA, RELIGIOUS, POETRY, ELEGY, AUTOBIOGRAPHY, BIOGRAPHY, ROMANCE, KIDS, SELF_DEVELOPMENT, MUSIC, COOKING, ACADEMIC, SPORTS, OTHER;
}
